apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: jenkins
  labels:
    app: grafana
    component: core
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: grafana
    component: core
